version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-votacao
    restart: always
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: votacao
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-votacao
    restart: always
    ports:
      - "5672:5672"   # Porta para conexões de aplicativos (ex: Spring)
      - "15672:15672" # Porta para acessar o painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
